import { Header } from "@/components/Header/Header";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import Container from "@mui/material/Container";
import type { Metadata } from "next";
import "./globals.scss";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <Container maxWidth="lg">
            <Header />
          </Container>
          <main>
            <Container maxWidth="lg">{children}</Container>
          </main>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
