import { IRecipe } from "@/components/Recipe/IRecipe";

export const fakeRecipesData: IRecipe[] = [
  {
    title: "Recipe 1",
    slug: "recipe-1",
    desc: "Description 1",
    thumbnail: "/recipe.jpg",
    prep: "10 mins",
    bake: "1 hr to 1 hr 15 mins",
    total: "1 hr 25 mins",
    yield: "1 loaf, 12 generous servings",
    categories: ["Recipes", "Bread", "Quick Bread"],
  },
  {
    title: "Recipe 2",
    slug: "recipe-2",
    desc: "Description 2",
    thumbnail: "/recipe.jpg",
    prep: "10 mins",
    bake: "1 hr to 1 hr 15 mins",
    total: "1 hr 25 mins",
    yield: "1 loaf, 12 generous servings",
    categories: ["Recipes", "Bread", "Quick Bread"],
  },
  {
    title: "Recipe 3",
    slug: "recipe-3",
    desc: "Description 3",
    thumbnail: "/recipe.jpg",
    prep: "10 mins",
    bake: "1 hr to 1 hr 15 mins",
    total: "1 hr 25 mins",
    yield: "1 loaf, 12 generous servings",
    categories: ["Recipes", "Bread", "Quick Bread"],
  },
  {
    title: "Recipe 4",
    slug: "recipe-4",
    desc: "Description 4",
    thumbnail: "/recipe.jpg",
    prep: "10 mins",
    bake: "1 hr to 1 hr 15 mins",
    total: "1 hr 25 mins",
    yield: "1 loaf, 12 generous servings",
    categories: ["Recipes", "Bread", "Quick Bread"],
  },
  {
    title: "Recipe 5",
    slug: "recipe-5",
    desc: "Description 5",
    thumbnail: "/recipe.jpg",
    prep: "10 mins",
    bake: "1 hr to 1 hr 15 mins",
    total: "1 hr 25 mins",
    yield: "1 loaf, 12 generous servings",
    categories: ["Recipes", "Bread", "Quick Bread"],
  },
  {
    title: "Recipe 6",
    slug: "recipe-6",
    desc: "Description 6",
    thumbnail: "/recipe.jpg",
    prep: "10 mins",
    bake: "1 hr to 1 hr 15 mins",
    total: "1 hr 25 mins",
    yield: "1 loaf, 12 generous servings",
    categories: ["Recipes", "Bread", "Quick Bread"],
  },
  {
    title: "Recipe 7",
    slug: "recipe-7",
    desc: "Description 7",
    thumbnail: "/recipe.jpg",
    prep: "10 mins",
    bake: "1 hr to 1 hr 15 mins",
    total: "1 hr 25 mins",
    yield: "1 loaf, 12 generous servings",
    categories: ["Recipes", "Bread", "Quick Bread"],
  },
  {
    title: "Recipe 8",
    slug: "recipe-8",
    desc: "Description 8",
    thumbnail: "/recipe.jpg",
    prep: "10 mins",
    bake: "1 hr to 1 hr 15 mins",
    total: "1 hr 25 mins",
    yield: "1 loaf, 12 generous servings",
    categories: ["Recipes", "Bread", "Quick Bread"],
  },
  {
    title: "Recipe 9",
    slug: "recipe-9",
    desc: "Description 9",
    thumbnail: "/recipe.jpg",
    prep: "10 mins",
    bake: "1 hr to 1 hr 15 mins",
    total: "1 hr 25 mins",
    yield: "1 loaf, 12 generous servings",
    categories: ["Recipes", "Bread", "Quick Bread"],
  },
];
